// gen_inert_table — build-time generator for the NFKC_Casefold inert range
// table used by text_utils.hpp's fast path. Iterates every BMP non-ASCII
// codepoint, marks those for which NFKC_Casefold is the identity AND
// combining class is 0, merges into ranges, and emits a header.

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include <utf8proc.h>

namespace {

std::string encode_utf8(char32_t cp) {
    std::string s;
    if (cp < 0x80) {
        s.push_back(static_cast<char>(cp));
    } else if (cp < 0x800) {
        s.push_back(static_cast<char>(0xC0 | (cp >> 6)));
        s.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
    } else if (cp < 0x10000) {
        s.push_back(static_cast<char>(0xE0 | (cp >> 12)));
        s.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
        s.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
    } else if (cp <= 0x10FFFF) {
        s.push_back(static_cast<char>(0xF0 | (cp >> 18)));
        s.push_back(static_cast<char>(0x80 | ((cp >> 12) & 0x3F)));
        s.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
        s.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
    }
    return s;
}

std::string nfkc_casefold(std::string_view in) {
    utf8proc_uint8_t* out = nullptr;
    auto n = utf8proc_map(
        reinterpret_cast<const utf8proc_uint8_t*>(in.data()),
        static_cast<utf8proc_ssize_t>(in.size()), &out,
        static_cast<utf8proc_option_t>(UTF8PROC_STABLE | UTF8PROC_COMPOSE |
                                       UTF8PROC_COMPAT | UTF8PROC_CASEFOLD |
                                       UTF8PROC_IGNORE));
    if (n < 0 || out == nullptr) return {};
    std::string result(reinterpret_cast<const char*>(out),
                       static_cast<std::size_t>(n));
    std::free(out);
    return result;
}

struct Range {
    char32_t lo;
    char32_t hi;
};

bool is_inert(char32_t cp) {
    // Surrogate halves (D800..DFFF) are not valid scalar values;
    // utf8proc treats them as errors and the oracle test sweeps them.
    if (cp >= 0xD800 && cp <= 0xDFFF) return false;

    // CCC > 0 means a combining mark. Such codepoints cannot be
    // inert in a multi-codepoint string — they'd reorder with the
    // preceding starter, and our per-codepoint check is context-free.
    const auto* prop = utf8proc_get_property(static_cast<utf8proc_int32_t>(cp));
    if (prop == nullptr) return false;
    if (prop->combining_class != 0) return false;

    auto u = encode_utf8(cp);
    if (u.empty()) return false;
    return nfkc_casefold(u) == u;
}

}  // namespace

int main(int argc, char** argv) {
    if (argc != 2) {
        std::fprintf(stderr, "usage: %s <output.hpp>\n", argv[0]);
        return 1;
    }
    const char* out_path = argv[1];

    std::vector<Range> ranges;
    char32_t run_lo = 0;
    char32_t run_hi = 0;
    bool in_run = false;

    auto flush = [&]() {
        if (in_run) {
            ranges.push_back({run_lo, run_hi});
            in_run = false;
        }
    };

    for (char32_t cp = 0x80; cp <= 0xFFFF; ++cp) {
        if (is_inert(cp)) {
            if (!in_run) {
                run_lo = cp;
                run_hi = cp;
                in_run = true;
            } else {
                run_hi = cp;
            }
        } else {
            flush();
        }
    }
    flush();

    FILE* fp = std::fopen(out_path, "wb");
    if (fp == nullptr) {
        std::fprintf(stderr, "gen_inert_table: cannot open %s\n", out_path);
        return 1;
    }

    std::fprintf(fp,
                 "// AUTO-GENERATED by tools/gen_inert_table.cpp — DO NOT EDIT.\n"
                 "// Source: utf8proc v%s (Unicode %s).\n"
                 "// Definition of 'inert':\n"
                 "//   1. NFKC_Casefold(cp) == cp  (utf8proc_map with\n"
                 "//      STABLE|COMPOSE|COMPAT|CASEFOLD|IGNORE returns the input bytes)\n"
                 "//   2. utf8proc_get_property(cp)->combining_class == 0\n"
                 "//   3. cp is not a surrogate half (D800..DFFF)\n"
                 "//\n"
                 "// Exhaustive oracle test: tests/analyzer_test.cpp\n"
                 "//   NfkcInert::TableOracleExhaustive — re-validates every\n"
                 "//   codepoint in this table against utf8proc at test time;\n"
                 "//   a stale or wrong table turns that test red.\n"
                 "#pragma once\n"
                 "\n"
                 "#include <cstdint>\n"
                 "\n"
                 "namespace bitcask::text::detail {\n"
                 "\n"
                 "[[nodiscard]] inline bool nfkc_casefold_inert(char32_t cp) noexcept {\n",
                 utf8proc_version(), utf8proc_unicode_version());

    if (ranges.empty()) {
        std::fprintf(fp, "    (void)cp;\n"
                         "    return false;\n");
    } else {
        std::fprintf(fp,
                     "    // %zu range%s covering %zu codepoints.\n",
                     ranges.size(), ranges.size() == 1 ? "" : "s",
                     [&] {
                         std::size_t total = 0;
                         for (const auto& r : ranges) total += r.hi - r.lo + 1;
                         return total;
                     }());
        for (const auto& r : ranges) {
            if (r.lo == r.hi) {
                std::fprintf(fp, "    if (cp == 0x%X) return true;\n",
                             static_cast<unsigned>(r.lo));
            } else {
                std::fprintf(fp,
                             "    if (cp >= 0x%X && cp <= 0x%X) return true;\n",
                             static_cast<unsigned>(r.lo),
                             static_cast<unsigned>(r.hi));
            }
        }
        std::fprintf(fp, "    return false;\n");
    }

    std::fprintf(fp, "}\n"
                     "\n"
                     "}  // namespace bitcask::text::detail\n");

    if (std::fclose(fp) != 0) {
        std::fprintf(stderr, "gen_inert_table: write failed for %s\n", out_path);
        return 1;
    }

    std::printf("gen_inert_table: wrote %zu range(s) to %s\n",
                ranges.size(), out_path);
    return 0;
}
