// gen_inert_table — build-time generator for the NFKC_Casefold inert range
// table used by text_utils.hpp's fast path. Iterates every BMP non-ASCII
// codepoint, marks those ICU reports as normalization-inert under
// NFKC_Casefold, merges into ranges, and emits a header.
//
// S38: the inertness predicate moved from a hand-rolled
// "NFKC_Casefold(cp) == cp && ccc == 0" to ICU's Normalizer2::isInert.
// That was a bug fix, not just a library swap. The old predicate missed the
// third requirement — "does not combine with a neighbour" — so it marked
// composable starters with ccc == 0 as inert. The fast path is context-free
// per codepoint, so such a pair sailed through uncomposed:
//
//   U+1100 U+1161 (Hangul jamo)  should fold to U+AC00 "가"
//   old fast path emitted the two jamo unchanged
//
// i.e. the same Korean word written precomposed vs decomposed produced
// different terms and could not match itself. ICU's isInert is exactly the
// three-part predicate we need; it is a strict subset of the old one
// (875 BMP codepoints dropped, none added).

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <vector>

#include <unicode/normalizer2.h>
#include <unicode/uchar.h>
#include <unicode/uversion.h>

#include "bitcask/detail/icu_util.hpp"

namespace {

struct Range {
    char32_t lo;
    char32_t hi;
};

bool is_inert(char32_t cp) {
    // Surrogate halves (D800..DFFF) are not valid scalar values.
    if (cp >= 0xD800 && cp <= 0xDFFF) return false;

    // ICU's isInert is the full three-part predicate: NFKC_Casefold maps the
    // codepoint to itself, ccc == 0, and it does not combine with either
    // neighbour. All three are required for a context-free per-codepoint
    // fast path to be correct.
    return bitcask::text::detail::icu_is_nfkc_cf_inert(cp);
}

}  // namespace

int main(int argc, char** argv) {
    if (argc != 2) {
        std::fprintf(stderr, "usage: %s <output.hpp>\n", argv[0]);
        return 1;
    }
    const char* out_path = argv[1];

    std::vector<Range> ranges;
    char32_t run_lo = 0;
    char32_t run_hi = 0;
    bool in_run = false;

    auto flush = [&]() {
        if (in_run) {
            ranges.push_back({run_lo, run_hi});
            in_run = false;
        }
    };

    for (char32_t cp = 0x80; cp <= 0xFFFF; ++cp) {
        if (is_inert(cp)) {
            if (!in_run) {
                run_lo = cp;
                run_hi = cp;
                in_run = true;
            } else {
                run_hi = cp;
            }
        } else {
            flush();
        }
    }
    flush();

    FILE* fp = std::fopen(out_path, "wb");
    if (fp == nullptr) {
        std::fprintf(stderr, "gen_inert_table: cannot open %s\n", out_path);
        return 1;
    }

    std::fprintf(fp,
                 "// AUTO-GENERATED by tools/gen_inert_table.cpp — DO NOT EDIT.\n"
                 "// Source: ICU %s (Unicode %s).\n"
                 "// Definition of 'inert' (icu::Normalizer2::isInert on nfkc_cf):\n"
                 "//   1. NFKC_Casefold(cp) == cp\n"
                 "//   2. combining class == 0\n"
                 "//   3. cp does not combine with either neighbour\n"
                 "//   4. cp is not a surrogate half (D800..DFFF)\n"
                 "//\n"
                 "// (3) is what makes a context-free per-codepoint fast path\n"
                 "// sound; dropping it lets composable starter pairs such as\n"
                 "// U+1100 U+1161 -> U+AC00 slip through uncomposed.\n"
                 "//\n"
                 "// Exhaustive oracle test: tests/analyzer_test.cpp\n"
                 "//   NfkcInert::TableOracleExhaustive — re-validates every\n"
                 "//   codepoint in this table against ICU at test time;\n"
                 "//   a stale or wrong table turns that test red.\n"
                 "#pragma once\n"
                 "\n"
                 "#include <cstdint>\n"
                 "\n"
                 "namespace bitcask::text::detail {\n"
                 "\n"
                 "[[nodiscard]] inline bool nfkc_casefold_inert(char32_t cp) noexcept {\n",
                 bitcask::text::detail::icu_version(),
                 bitcask::text::detail::icu_unicode_version());

    if (ranges.empty()) {
        std::fprintf(fp, "    (void)cp;\n"
                         "    return false;\n");
    } else {
        std::fprintf(fp,
                     "    // %zu range%s covering %zu codepoints.\n",
                     ranges.size(), ranges.size() == 1 ? "" : "s",
                     [&] {
                         std::size_t total = 0;
                         for (const auto& r : ranges) total += r.hi - r.lo + 1;
                         return total;
                     }());
        for (const auto& r : ranges) {
            if (r.lo == r.hi) {
                std::fprintf(fp, "    if (cp == 0x%X) return true;\n",
                             static_cast<unsigned>(r.lo));
            } else {
                std::fprintf(fp,
                             "    if (cp >= 0x%X && cp <= 0x%X) return true;\n",
                             static_cast<unsigned>(r.lo),
                             static_cast<unsigned>(r.hi));
            }
        }
        std::fprintf(fp, "    return false;\n");
    }

    std::fprintf(fp, "}\n"
                     "\n"
                     "}  // namespace bitcask::text::detail\n");

    if (std::fclose(fp) != 0) {
        std::fprintf(stderr, "gen_inert_table: write failed for %s\n", out_path);
        return 1;
    }

    std::printf("gen_inert_table: wrote %zu range(s) to %s\n",
                ranges.size(), out_path);
    return 0;
}
